import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import { DM_Serif_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const Serif = DM_Serif_Display({
  subsets : ["latin"],
  style : "normal",
  weight : "400"
})
const playfair_italic = Playfair_Display({
  subsets : ["latin"],
  style : "italic"
})

export const metadata: Metadata = {
  title: "Interior Design",
  description: "Generated by Fiza Rafakat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {` ${Serif.className} max-w-[1440px] mx-auto `}>{children}</body>
    </html>
  );
}
